plugins {
    id 'java'
    id 'jacoco'
    id 'war'
}

group = 'com.booking.bus'
version = '1.0-SNAPSHOT'

repositories {
    maven { url 'https://maven.aliyun.com/repository/public' }
    mavenCentral()
}

dependencies {
    providedCompile 'javax.servlet:javax.servlet-api:3.1.0'
    implementation 'javax.servlet:jstl:1.2'

    // Hibernate 5.6
    implementation 'org.hibernate:hibernate-core:5.6.15.Final'
    implementation 'org.hibernate:hibernate-entitymanager:5.6.15.Final'

    // PostgreSQL
    implementation 'org.postgresql:postgresql:42.5.0'
    implementation 'com.vladmihalcea:hibernate-types-52:2.21.1'

    // Logging
    implementation 'org.slf4j:slf4j-simple:2.0.9'

    implementation 'com.fasterxml.jackson.core:jackson-databind:2.13.0'
    implementation 'com.fasterxml.jackson.core:jackson-core:2.13.0'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.13.0'

    // Test
    testImplementation 'org.testng:testng:7.8.0'
    testImplementation 'com.h2database:h2:2.2.224'
}


tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
    sourceCompatibility = '17'
    targetCompatibility = '17'
}

test {
    useTestNG()
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = false
        html.required = true
        csv.required = false
    }
}

war {
    archiveFileName = 'bus-booking-05.war'
    from 'src/main/webapp'
}
