TRUNCATE TABLE seat_occupancies CASCADE;
TRUNCATE TABLE bookings CASCADE;
TRUNCATE TABLE fares CASCADE;
TRUNCATE TABLE seats CASCADE;
TRUNCATE TABLE route_stops CASCADE;
TRUNCATE TABLE routes CASCADE;
TRUNCATE TABLE clients CASCADE;
TRUNCATE TABLE companies CASCADE;

ALTER SEQUENCE companies_id_seq RESTART WITH 1;
ALTER SEQUENCE routes_id_seq RESTART WITH 1;
ALTER SEQUENCE route_stops_id_seq RESTART WITH 1;
ALTER SEQUENCE fares_id_seq RESTART WITH 1;
ALTER SEQUENCE clients_id_seq RESTART WITH 1;
ALTER SEQUENCE bookings_id_seq RESTART WITH 1;
ALTER SEQUENCE seats_id_seq RESTART WITH 1;
ALTER SEQUENCE seat_occupancies_id_seq RESTART WITH 1;
